### PR TITLE
Included umlauts and German sz into the macros

### PR DESCRIPTION
**Pull request by TheOneWithTheBraid**
Included umlauts and German sz into the macros

### CODE REVIEW

**Comment by marvinborner** [comment]
I'm not sure this complies with the c89 std, but wth!

**Comment by TheOneWithTheBraid** [comment]
Could you add the `hacktoberfest-accepted` label?

**Comment by marvinborner** [comment]
Like that?

**Comment by marvinborner** [comment]
By the way, UTF-8 identifiers only work with a conversion script. I've added this in 5be431b.

More information: https://gcc.gnu.org/wiki/FAQ#utf8_identifiers

**Pull request merged**
